# Generated by Django 5.1.5 on 2025-04-15 03:18

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mets', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('weight_value', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('weight_unit', models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds')], default='kg', max_length=3)),
                ('target_calories', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('calories_per_min', models.FloatField(editable=False)),
                ('required_minutes', models.FloatField(editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
